name: Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCES_KEY_SECRET: ${{ secrets.AWS_ACCES_KEY_SECRET }}
        run:
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t hello:$rev
          docker tag hello:$rev 244530008913.dkr.ecr.eu-west-1.amazonaws.com/esha014:$rev
          docker tag hello:$rev 244530008913.dkr.ecr.eu-west-1.amazonaws.com/esha014:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/esha014:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/esha014:latest